### ISSUE TITLE
Support for video files

### ISSUE THREAD

**Issue by thefotios** [hybridgroup/cylon-opencv#14]
I'm not sure how entailed this would be, but is it possible to add support for using video files as input sources?

`node-opencv` is able to do it, not sure if you can utilize any of their work <sup>[1]</sup>.

[1]: https://github.com/peterbraden/node-opencv/blob/master/examples/motion-track.js#L5

**Comment by edgarsilva** [comment]
I just noticed I forgot to update this issue, this should be possible with the latest versions of the module. In case you want to give it a try, let me know how it goes.
