### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by slickboy** [hybridgroup/cylon-opencv#16]
I am trying to install cylon-opencv. I have already managed to build opencv on my computer but when I run the command "npm install cylon-opencv" I get errors. It tells me to tell the author that node-pre-gyp install --fallback-to-build has failed on my system. What can I do to fix this??

**Comment by edgarsilva** [comment]
Did you have any luck with the instaltion of opencv and testing this? I'm closing this issue.

Let us know if you were able (or not) to make it work.
