### ISSUE TITLE
problem with npm install opencv and npm install cylon-opencv

### ISSUE THREAD

**Issue by rauriemo** [hybridgroup/cylon-opencv#19]
brew installed opencv, now trying to npm intstall opencv and opencv-cylon, would really appreciate the help, getting the following error:

 node-pre-gyp was bundled with opencv@3.0.0, but bundled package wasn't found in unpacked tree

> opencv@3.0.0 install /usr/local/Cellar/node_modules/opencv
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/opencv/src/init.o
In file included from ../src/init.cc:5:
../src/CascadeClassifierWrap.h:5:3: error: no type named 'CascadeClassifier' in namespace
      'cv'; did you mean 'CascadeClassifierWrap'?
        cv::CascadeClassifier cc;
        ^~~~~~~~~~~~~~~~~~~~~
        CascadeClassifierWrap
../src/CascadeClassifierWrap.h:3:7: note: 'CascadeClassifierWrap' declared here
class CascadeClassifierWrap: public node::ObjectWrap {
      ^
In file included from ../src/init.cc:6:
../src/VideoCaptureWrap.h:5:7: error: no type named 'VideoCapture' in namespace 'cv'; did
      you mean 'VideoCaptureWrap'?
      cv::VideoCapture cap;
      ^~~~~~~~~~~~~~~~
      VideoCaptureWrap
../src/VideoCaptureWrap.h:3:7: note: 'VideoCaptureWrap' declared here
class VideoCaptureWrap: public node::ObjectWrap {
      ^
2 errors generated.
make: *** [Release/obj.target/opencv/src/init.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=opencv" "--configuration=Release" "--module_name=opencv" "--version=3.0.0" "--major=3" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/opencv" "--host=https://node-opencv.s3.amazonaws.com/" "--module_path=/usr/local/Cellar/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64" "--module=/usr/local/Cellar/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node" "--remote_path=./opencv/v3.0.0/Release/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz" "--hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/" "--hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /usr/local/Cellar/node_modules/opencv
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/usr/local/Cellar/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64 --module=/usr/local/Cellar/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node_modules/opencv/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1015:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/usr/local/Cellar/node_modules/opencv/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/Cellar/node_modules/opencv
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.5.31
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=opencv --configuration=Release --module_name=opencv --version=3.0.0 --major=3 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/opencv --host=https://node-opencv.s3.amazonaws.com/ --module_path=/usr/local/Cellar/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64 --module=/usr/local/Cellar/node_modules/opencv/build/opencv/v3.0.0/Release/node-v14-darwin-x64/opencv.node --remote_path=./opencv/v3.0.0/Release/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz --hosted_path=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/ --hosted_tarball=https://node-opencv.s3.amazonaws.com/opencv/v3.0.0/Release/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "opencv"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! opencv@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencv@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the opencv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/Cellar/npm-debug.log

Thanks!

**Comment by edgarsilva** [comment]
I think there is an issue with the brew version of opencv. You might need to install another version of opencv manually. @stewart can you comment or provide some thoughts into this, I do not have a Mac to test any of this.

**Comment by stewart** [comment]
Hi @rauriemo - It looks like you don't have `opencv` installed, which is a pre-requisite for installing the NPM package.

For Homebrew:

    brew tap homebrew/science
    brew install opencv

**Comment by rauriemo** [comment]
hey guys, thanks so much for the tips. It was a versioning issue indeed, I updated to version 3.0.0 and it worked perfectly.
